### PR TITLE
[#256] Fix partiality in 'cycle'

### LINKED ISSUE #256: Fix partiality in 'cycle'
To my big surprise, the `cycle` function from `base` is partial: it fails on empty lists

```haskell
ghci> :t cycle
cycle :: [a] -> [a]
ghci> cycle []
*** Exception: Prelude.cycle: empty list
```

It's a bit problematic, since we don't want to expose partial functions. I see the following options:

1. Don't reexport `cycle`.
2. Change its type to `NonEmpty a -> NonEmpty a`.
3. Reimplement manually by returning empty list when empty list is given.

@vrom911, what do you think?

### PR DESCRIPTION
**Pull request by chshersh**
Resolves #256

### CODE REVIEW

File: src/Relude/List/Reexport.hs [hunk 1]
```diff
@@ -55,6 +56,18 @@ import qualified Data.List.NonEmpty as NE (head, init, last, tail)
 -- $setup
 -- >>> import Relude
 
+{- | Creates an infinite list from a finite list by appending the
```
Comment (vrom911) [inline src/Relude/List/Reexport.hs:59]: Maybe add the difference with the `cycle` from `Data.List` in here?
